name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: "13"
      - run: npm ci
      - run: npm run test
      - run: npm run lint
      - run: npx @coralproject/package-version-lint
